export const formStructure = {
  startQuestion: "purpose",
  finalQuestion: "additional_info", // This is the last question in the flow
  sections: [
    {
      id: "intro",
      title: "Introduction",
      questions: ["purpose"],
    },
    {
      id: "details",
      title: "Project Details",
      questions: [
        "business_type",
        "startup_stage",
        "funding_status",
        "enterprise_industry",
        "tech_focus",
        "ai_application",
        "healthcare_focus",
        "finance_focus",
        "retail_focus",
        "other_industry",
        "agency_specialization",
        "marketing_services",
        "development_focus",
        "frontend_tech",
        "backend_tech",
        "mobile_platforms",
        "cross_platform_tech",
        "design_focus",
        "nonprofit_mission",
        "business_other",
        "personal_type",
        "website_purpose",
        "website_features",
        "ecommerce_products",
        "website_other_purpose",
        "website_timeline",
        "app_platform",
        "app_purpose",
        "app_features",
        "portfolio_purpose",
        "portfolio_field",
        "portfolio_other_purpose",
        "blog_topic",
        "blog_audience",
        "personal_other",
        "feedback_type",
        "product_feedback",
        "product_positive",
        "product_improvement",
        "service_feedback",
        "service_positive",
        "service_improvement",
        "website_feedback",
        "website_design_feedback",
        "website_content_feedback",
        "website_usability_feedback",
        "website_performance_feedback",
        "suggestion_details",
        "feedback_other",
        "feedback_details",
        "contact_permission",
        "research_purpose",
        "research_industry",
        "research_other_industry",
        "academic_field",
        "research_timeline",
        "research_goals",
        "partnership_type",
        "partnership_other",
        "partnership_goals",
        "partnership_timeline",
      ],
    },
    {
      id: "business",
      title: "Business Information",
      questions: [
        "company_size",
        "business_goals",
        "growth_areas",
        "efficiency_areas",
        "launch_timeline",
        "funding_amount",
        "other_goals",
        "budget",
        "timeline",
        "decision_makers",
        "personal_budget",
        "personal_timeline",
      ],
    },
    {
      id: "contact",
      title: "Contact Information",
      questions: ["contact_info", "name", "phone", "additional_info"],
    },
  ],
  questions: {
    purpose: {
      id: "purpose",
      type: "radio",
      question: "What brings you here today?",
      required: true,
      section: "intro",
      options: [
        { value: "business", label: "Business inquiry", nextQuestion: "business_type" },
        { value: "personal", label: "Personal project", nextQuestion: "personal_type" },
        { value: "feedback", label: "Providing feedback", nextQuestion: "feedback_type" },
        { value: "research", label: "Market research", nextQuestion: "research_purpose" },
        { value: "partnership", label: "Partnership opportunity", nextQuestion: "partnership_type" },
      ],
    },
    // ... rest of the questions (same as in the original component)
    contact_info: {
      id: "contact_info",
      type: "text",
      question: "What's your email address?",
      required: true,
      section: "contact",
      nextQuestion: "name",
    },
    name: {
      id: "name",
      type: "text",
      question: "What's your name?",
      required: true,
      section: "contact",
      nextQuestion: "phone",
    },
    phone: {
      id: "phone",
      type: "text",
      question: "What's your phone number? (optional)",
      section: "contact",
      nextQuestion: "additional_info",
    },
    additional_info: {
      id: "additional_info",
      type: "textarea",
      question: "Is there anything else you'd like to share with us?",
      section: "contact",
      nextQuestion: null,
    },
  },
}
